### ISSUE TITLE
plot_gPrior Function Error

### ISSUE THREAD

**Issue by mdinh186** [GeoStat-Bayesian/exPrior#1]
When I tried to test function plot_gPrior on my rscript with the script below, it gives me error: 
******script******
library(gPrior)

meas = c(c(2,3,5),c(5,4),c(1,5,3,2))

theta=seq(from=-10,to=10,by=0.1)
res_gPrior = generalFromMeas(meas,theta)
plot_gPrior(res_gPrior, T)

*****Error******
Error in rainbow(length(measList)) : object 'measList' not found

**Comment by kcucchi** [comment]
I fixed the bug.

Also, measurements should be provided as a list of numerical vectors, where each element in the list corresponds to one site.
I added an error catch to raise an error when this is not the case.
